# Generated by Django 5.1.2 on 2024-12-16 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='musicians',
            field=models.ManyToManyField(related_name='bands_musicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
